services:
  db: 
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=geheim
      - MARIADB_DATABASE=cash
      - MARIADB_USER=cash
      - MARIADB_PASSWORD=geheimes-passwort
    restart: on-failure:10
    volumes: 
      - db-vol:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  pma: 
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 6080:80
    restart: on-failure:10
    depends_on: 
      - db
      
  php:
    image: php:apache
    volumes:
      - var/www/html
    ports:
      - 6081:80
    depends_on:
      - db
volumes: 
  db-vol:
    name: db-vol-name5
